"""
Public REST API (JSON).

Read endpoints are open. Write endpoints require `JUPR_WRITE_API_KEY` when set.
OpenAPI is auto-generated by FastAPI at /api/docs and /api/openapi.json.
"""

from __future__ import annotations

from typing import List, Optional

from fastapi import APIRouter, Depends, HTTPException, Query, Request, status
from pydantic import BaseModel, Field
from sqlalchemy.orm import Session

from web.auth import require_write_key
from web.db import get_session
from web.models import JuprPlayer
from web.services import dupr_forecast as dupr_forecast_svc
from web.services import dupr_live
from web.services import forecast as forecast_svc
from web.services import fupr as fupr_svc
from web.services import goal as goal_svc
from web.services import jupr as jupr_svc
from web.services import shadow as shadow_svc

router = APIRouter(prefix="/api", tags=["api"])


# ---------- schemas -----------------------------------------------------------

class ForecastRequest(BaseModel):
    r1: float = Field(..., ge=1.0, le=8.5)
    r2: float = Field(..., ge=1.0, le=8.5)
    r3: float = Field(..., ge=1.0, le=8.5)
    r4: float = Field(..., ge=1.0, le=8.5)
    target: int = Field(22, ge=14, le=33, description="Winner's minimum match-total (sum of game points)")
    rel1: Optional[float] = None
    rel2: Optional[float] = None
    rel3: Optional[float] = None
    rel4: Optional[float] = None


class PlayerImpactDTO(BaseModel):
    player: int
    pre_rating: float
    delta: float
    post_rating: float


class ForecastRowDTO(BaseModel):
    games1: int
    games2: int
    winner: int
    expected_games_team1: float
    impacts: List[PlayerImpactDTO]


class ForecastResponse(BaseModel):
    expected_games_team1: float
    rows: List[ForecastRowDTO]


class JuprPlayerDTO(BaseModel):
    id: int
    full_name: str
    dupr_id: Optional[str] = None
    seed_rating: float
    seed_reliability: float


class CreatePlayerRequest(BaseModel):
    full_name: str = Field(..., min_length=1, max_length=128)
    seed_rating: float = Field(3.0, ge=1.0, le=8.5)
    seed_reliability: float = Field(50.0, ge=0.0, le=100.0)
    dupr_id: Optional[str] = Field(default=None, max_length=64)


class RecordGameRequest(BaseModel):
    team1: List[int] = Field(..., min_length=2, max_length=2)
    team2: List[int] = Field(..., min_length=2, max_length=2)
    games1: int = Field(..., ge=0)
    games2: int = Field(..., ge=0)
    notes: Optional[str] = Field(default=None, max_length=500)


class JuprRatingDTO(BaseModel):
    player_id: int
    full_name: str
    seed_rating: float
    current_rating: float
    games_played: int
    last_delta: Optional[float] = None


class GameDTO(BaseModel):
    id: int
    team1: List[int]
    team2: List[int]
    pre_ratings: List[float]
    games1: int
    games2: int
    winner: int
    played_at: str


class FuprVoteRequest(BaseModel):
    rating: float = Field(..., ge=fupr_svc.MIN_RATING, le=fupr_svc.MAX_RATING)
    confidence: int = Field(3, ge=1, le=5)
    comment: Optional[str] = Field(default=None, max_length=280)


class FuprAggregateDTO(BaseModel):
    player_id: int
    count: int
    weighted_mean: Optional[float] = None
    median: Optional[float] = None
    histogram: dict


# ---------- forecast ----------------------------------------------------------

@router.post("/forecast", response_model=ForecastResponse, summary="Forecast rating impact for every score")
def api_forecast(req: ForecastRequest):
    rows = forecast_svc.forecast_matrix(
        req.r1, req.r2, req.r3, req.r4,
        target=req.target,
        rel1=req.rel1, rel2=req.rel2, rel3=req.rel3, rel4=req.rel4,
    )
    return ForecastResponse(
        expected_games_team1=rows[0].expected_games_team1 if rows else 0.0,
        rows=[
            ForecastRowDTO(
                games1=row.games1,
                games2=row.games2,
                winner=row.winner,
                expected_games_team1=row.expected_games_team1,
                impacts=[
                    PlayerImpactDTO(
                        player=imp.player,
                        pre_rating=imp.pre_rating,
                        delta=imp.delta,
                        post_rating=imp.post_rating,
                    )
                    for imp in row.impacts
                ],
            )
            for row in rows
        ],
    )


# ---------- JUPR players ------------------------------------------------------

def _player_to_dto(p: JuprPlayer) -> JuprPlayerDTO:
    return JuprPlayerDTO(
        id=p.id,
        full_name=p.full_name,
        dupr_id=p.dupr_id,
        seed_rating=p.seed_rating,
        seed_reliability=p.seed_reliability,
    )


@router.get("/jupr/players", response_model=List[JuprPlayerDTO])
def list_players(
    q: Optional[str] = Query(default=None, description="Substring search on full_name"),
    limit: int = Query(default=50, ge=1, le=200),
    session: Session = Depends(get_session),
):
    from sqlalchemy import select as _sel

    stmt = _sel(JuprPlayer).order_by(JuprPlayer.full_name).limit(limit)
    if q:
        stmt = _sel(JuprPlayer).where(JuprPlayer.full_name.ilike(f"%{q}%")).order_by(JuprPlayer.full_name).limit(limit)
    rows = session.execute(stmt).scalars().all()
    return [_player_to_dto(p) for p in rows]


@router.post(
    "/jupr/players",
    response_model=JuprPlayerDTO,
    status_code=status.HTTP_201_CREATED,
    dependencies=[Depends(require_write_key)],
)
def create_player(req: CreatePlayerRequest, session: Session = Depends(get_session)):
    p = jupr_svc.create_player(
        session,
        full_name=req.full_name,
        seed_rating=req.seed_rating,
        seed_reliability=req.seed_reliability,
        dupr_id=req.dupr_id,
    )
    return _player_to_dto(p)


@router.get("/jupr/players/{player_id}", response_model=JuprRatingDTO)
def get_player_rating(player_id: int, session: Session = Depends(get_session)):
    r = jupr_svc.get_rating(session, player_id)
    if r is None:
        raise HTTPException(status_code=404, detail="player not found")
    return JuprRatingDTO(
        player_id=r.player_id,
        full_name=r.full_name,
        seed_rating=r.seed_rating,
        current_rating=r.current_rating,
        games_played=r.games_played,
        last_delta=r.last_delta,
    )


@router.get("/jupr/players/{player_id}/games", response_model=List[GameDTO])
def get_player_games(
    player_id: int,
    limit: int = Query(default=50, ge=1, le=200),
    session: Session = Depends(get_session),
):
    games = jupr_svc.recent_games(session, player_id=player_id, limit=limit)
    return [
        GameDTO(
            id=g.id,
            team1=[g.team1_p1_id, g.team1_p2_id],
            team2=[g.team2_p1_id, g.team2_p2_id],
            pre_ratings=[g.pre_r1, g.pre_r2, g.pre_r3, g.pre_r4],
            games1=g.games1,
            games2=g.games2,
            winner=g.winner,
            played_at=g.played_at.isoformat() if g.played_at else "",
        )
        for g in games
    ]


# ---------- JUPR games --------------------------------------------------------

@router.post(
    "/jupr/games",
    response_model=GameDTO,
    status_code=status.HTTP_201_CREATED,
    dependencies=[Depends(require_write_key)],
)
def record_game(req: RecordGameRequest, session: Session = Depends(get_session)):
    try:
        g = jupr_svc.record_game(
            session,
            team1=req.team1,
            team2=req.team2,
            games1=req.games1,
            games2=req.games2,
            notes=req.notes,
        )
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e))
    return GameDTO(
        id=g.id,
        team1=[g.team1_p1_id, g.team1_p2_id],
        team2=[g.team2_p1_id, g.team2_p2_id],
        pre_ratings=[g.pre_r1, g.pre_r2, g.pre_r3, g.pre_r4],
        games1=g.games1,
        games2=g.games2,
        winner=g.winner,
        played_at=g.played_at.isoformat() if g.played_at else "",
    )


@router.get("/jupr/leaderboard", response_model=List[JuprRatingDTO])
def api_leaderboard(
    limit: int = Query(default=50, ge=1, le=200),
    session: Session = Depends(get_session),
):
    board = jupr_svc.leaderboard(session, limit=limit)
    return [
        JuprRatingDTO(
            player_id=r.player_id,
            full_name=r.full_name,
            seed_rating=r.seed_rating,
            current_rating=r.current_rating,
            games_played=r.games_played,
            last_delta=r.last_delta,
        )
        for r in board
    ]


# ---------- FUPR --------------------------------------------------------------

def _voter_key(request: Request) -> str:
    # Vercel puts the client IP in x-forwarded-for; fall back to peer addr.
    xff = request.headers.get("x-forwarded-for", "")
    if xff:
        return xff.split(",")[0].strip()
    return request.client.host if request.client else "anon"


@router.get("/fupr/{player_id}", response_model=FuprAggregateDTO)
def api_fupr_aggregate(player_id: int, session: Session = Depends(get_session)):
    agg = fupr_svc.aggregate(session, player_id)
    return FuprAggregateDTO(
        player_id=agg.player_id,
        count=agg.count,
        weighted_mean=agg.weighted_mean,
        median=agg.median,
        histogram=agg.histogram,
    )


@router.post("/fupr/{player_id}/votes", status_code=status.HTTP_201_CREATED)
def api_fupr_vote(
    player_id: int,
    req: FuprVoteRequest,
    request: Request,
    session: Session = Depends(get_session),
):
    # Confirm player exists
    p = session.get(JuprPlayer, player_id)
    if p is None:
        raise HTTPException(status_code=404, detail="player not found")
    try:
        fupr_svc.cast_vote(
            session,
            player_id=player_id,
            rating=req.rating,
            confidence=req.confidence,
            voter_key=_voter_key(request),
            comment=req.comment,
        )
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e))
    agg = fupr_svc.aggregate(session, player_id)
    return FuprAggregateDTO(
        player_id=agg.player_id,
        count=agg.count,
        weighted_mean=agg.weighted_mean,
        median=agg.median,
        histogram=agg.histogram,
    )


@router.get("/health")
def health():
    return {"status": "ok", "service": "duprly-web"}


# ---------- DUPR player search (hybrid: cache + optional live) ----------------

class DuprHitDTO(BaseModel):
    dupr_id: str
    full_name: str
    doubles: Optional[float] = None
    doubles_reliability: Optional[float] = None
    singles: Optional[float] = None
    image_url: Optional[str] = None
    source: str
    stale: bool


@router.get("/dupr/search", response_model=List[DuprHitDTO])
def api_dupr_search(
    q: str = Query(..., min_length=1, max_length=64),
    limit: int = Query(default=15, ge=1, le=50),
    live: bool = Query(default=True, description="Fall back to live DUPR if configured"),
    session: Session = Depends(get_session),
):
    hits = dupr_live.search(session, query=q, limit=limit, live_fallback=live)
    return [
        DuprHitDTO(
            dupr_id=h.dupr_id,
            full_name=h.full_name,
            doubles=h.doubles,
            doubles_reliability=h.doubles_reliability,
            singles=h.singles,
            image_url=h.image_url,
            source=h.source,
            stale=h.stale,
        )
        for h in hits
    ]


@router.get("/dupr/players/{dupr_id}", response_model=DuprHitDTO)
def api_dupr_get(dupr_id: str, session: Session = Depends(get_session)):
    h = dupr_live.get_by_id(session, dupr_id)
    if h is None:
        raise HTTPException(status_code=404, detail="not in cache — try /refresh")
    return DuprHitDTO(
        dupr_id=h.dupr_id,
        full_name=h.full_name,
        doubles=h.doubles,
        doubles_reliability=h.doubles_reliability,
        singles=h.singles,
        image_url=h.image_url,
        source=h.source,
        stale=h.stale,
    )


@router.post(
    "/dupr/players/{dupr_id}/refresh",
    response_model=DuprHitDTO,
    dependencies=[Depends(require_write_key)],
)
def api_dupr_refresh(dupr_id: str, session: Session = Depends(get_session)):
    try:
        h = dupr_live.refresh(session, dupr_id)
    except RuntimeError as e:
        raise HTTPException(status_code=503, detail=str(e))
    if h is None:
        raise HTTPException(status_code=404, detail="DUPR returned no player for that id")
    return DuprHitDTO(
        dupr_id=h.dupr_id,
        full_name=h.full_name,
        doubles=h.doubles,
        doubles_reliability=h.doubles_reliability,
        singles=h.singles,
        image_url=h.image_url,
        source=h.source,
        stale=h.stale,
    )


# ---------- DUPR official forecast (live /match/v1.0/forecast) ---------------

class DuprForecastTeamIn(BaseModel):
    player1_id: int = Field(..., description="Numeric DUPR id (long). Paste from dashboard URL.")
    player2_id: Optional[int] = Field(
        default=None,
        description="Partner's numeric DUPR id for DOUBLES; omit for SINGLES.",
    )


class DuprForecastRequest(BaseModel):
    teams: List[DuprForecastTeamIn] = Field(..., min_length=2, max_length=2)
    winning_score: int = Field(11, ge=5, le=25, description="Game target (11/15/21).")
    event_format: str = Field("DOUBLES", pattern="^(DOUBLES|SINGLES)$")
    match_source: str = Field("CLUB", description="CLUB | TOURNAMENT | ...")
    match_type: str = Field("SIDE_ONLY", description="SIDE_ONLY | SIDE_AND_SERVE | ...")
    game_count: int = Field(1, ge=1, le=5)
    use_fixtures: bool = Field(
        False,
        description=(
            "Force-use Proxyman fixtures instead of live DUPR. Handy for local "
            "dev / CI. Also enabled via DUPRLY_USE_FIXTURES=1."
        ),
    )


class DuprForecastTeamDTO(BaseModel):
    player1_id: int
    player2_id: Optional[int]
    predicted_losing_score: Optional[float]
    win_probability_pct: Optional[float]
    rating_impacts: List[float]
    impact_if_blowout_win: Optional[float]
    impact_if_tight_win: Optional[float]


class DuprForecastDTO(BaseModel):
    source: str
    winning_score: int
    event_format: str
    match_source: str
    match_type: str
    game_count: int
    team_a: DuprForecastTeamDTO
    team_b: DuprForecastTeamDTO


def _team_to_dto(t) -> DuprForecastTeamDTO:
    return DuprForecastTeamDTO(
        player1_id=t.player1_id,
        player2_id=t.player2_id,
        predicted_losing_score=t.predicted_losing_score,
        win_probability_pct=t.win_probability_pct,
        rating_impacts=t.rating_impacts,
        impact_if_blowout_win=t.impact_if_blowout_win,
        impact_if_tight_win=t.impact_if_tight_win,
    )


def _forecast_to_dto(mf) -> DuprForecastDTO:
    return DuprForecastDTO(
        source=mf.source,
        winning_score=mf.winning_score,
        event_format=mf.event_format,
        match_source=mf.match_source,
        match_type=mf.match_type,
        game_count=mf.game_count,
        team_a=_team_to_dto(mf.team_a),
        team_b=_team_to_dto(mf.team_b),
    )


@router.post(
    "/dupr/expected-score",
    response_model=DuprForecastDTO,
    summary="DUPR official predicted game score",
    description=(
        "Thin wrapper over DUPR's `/match/v1.0/expected-score`. Returns only "
        "the predicted losing-side game count per team (no probability / "
        "rating impacts). Use `/api/dupr/forecast` for full rating-change "
        "curves."
    ),
)
def api_dupr_expected_score(req: DuprForecastRequest):
    teams = [(t.player1_id, t.player2_id) for t in req.teams]
    try:
        mf = dupr_forecast_svc.expected_score(
            teams,
            winning_score=req.winning_score,
            event_format=req.event_format,
            match_source=req.match_source,
            match_type=req.match_type,
            game_count=req.game_count,
            use_fixtures=req.use_fixtures,
        )
    except dupr_forecast_svc.DuprForecastUnavailable as e:
        raise HTTPException(status_code=503, detail=str(e))
    return _forecast_to_dto(mf)


@router.post(
    "/dupr/forecast",
    response_model=DuprForecastDTO,
    summary="DUPR official match forecast (rating impacts + win probability)",
    description=(
        "Thin wrapper over DUPR's `/match/v1.0/forecast`. Returns the full "
        "rating-impact curve (`rating_impacts[N]` = delta if this team wins "
        "and the losing team scored `N` games) plus `winProbabilityPercentage`."
        "\n\n"
        "Requires `DUPR_USERNAME`/`DUPR_PASSWORD` env vars for live calls. "
        "Set `use_fixtures: true` (or `DUPRLY_USE_FIXTURES=1`) to return the "
        "Proxyman-captured example response instead — useful in CI / local "
        "dev when live creds aren't configured."
    ),
)
def api_dupr_forecast(req: DuprForecastRequest):
    teams = [(t.player1_id, t.player2_id) for t in req.teams]
    try:
        mf = dupr_forecast_svc.forecast(
            teams,
            winning_score=req.winning_score,
            event_format=req.event_format,
            match_source=req.match_source,
            match_type=req.match_type,
            game_count=req.game_count,
            use_fixtures=req.use_fixtures,
        )
    except dupr_forecast_svc.DuprForecastUnavailable as e:
        raise HTTPException(status_code=503, detail=str(e))
    return _forecast_to_dto(mf)


# ---------- Goal forecast ("what do I have to win?") --------------------------

class GoalRequest(BaseModel):
    me_slot: int = Field(..., ge=1, le=4)
    r1: float = Field(..., ge=1.0, le=8.5)
    r2: float = Field(..., ge=1.0, le=8.5)
    r3: float = Field(..., ge=1.0, le=8.5)
    r4: float = Field(..., ge=1.0, le=8.5)
    target_delta: float = Field(..., ge=-1.0, le=1.0, description="e.g. +0.05 to gain five points")
    target: int = Field(22, ge=14, le=33, description="Winner's minimum match-total (sum of game points)")
    rel1: Optional[float] = None
    rel2: Optional[float] = None
    rel3: Optional[float] = None
    rel4: Optional[float] = None


class GoalRowDTO(BaseModel):
    games1: int
    games2: int
    winner: int
    my_delta: float
    my_post_rating: float
    hits_goal: bool
    gap_to_goal: float


class GoalForecastDTO(BaseModel):
    me_slot: int
    my_pre_rating: float
    target_delta: float
    best_case_delta: float
    worst_case_delta: float
    hits_goal: bool
    best_score: Optional[str]
    worst_score: Optional[str]
    rows: List[GoalRowDTO]


@router.post("/goal", response_model=GoalForecastDTO, summary="Reverse-forecast: what do I have to win?")
def api_goal(req: GoalRequest):
    try:
        forecast = goal_svc.compute(
            me_slot=req.me_slot,
            r1=req.r1, r2=req.r2, r3=req.r3, r4=req.r4,
            target_delta=req.target_delta,
            target=req.target,
            rel1=req.rel1, rel2=req.rel2, rel3=req.rel3, rel4=req.rel4,
        )
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e))
    return GoalForecastDTO(
        me_slot=forecast.me_slot,
        my_pre_rating=forecast.my_pre_rating,
        target_delta=forecast.target_delta,
        best_case_delta=forecast.best_case_delta,
        worst_case_delta=forecast.worst_case_delta,
        hits_goal=forecast.hits_goal,
        best_score=forecast.best_score,
        worst_score=forecast.worst_score,
        rows=[
            GoalRowDTO(
                games1=r.games1,
                games2=r.games2,
                winner=r.winner,
                my_delta=r.my_delta,
                my_post_rating=r.my_post_rating,
                hits_goal=r.hits_goal,
                gap_to_goal=r.gap_to_goal,
            )
            for r in forecast.rows
        ],
    )


# ---------- Shadow reset simulator -------------------------------------------

class ShadowResetRequest(BaseModel):
    dupr_id: str = Field(..., min_length=1, max_length=64)
    baseline_rating: Optional[float] = Field(
        default=None,
        ge=1.0,
        le=8.5,
        description=(
            "Your pre-reset rating (e.g. what DUPR showed for you on/before "
            "`cutoff_date`). If omitted we use the pre-match rating of your "
            "earliest eligible match, or your current doubles rating."
        ),
    )
    cutoff_date: Optional[str] = Field(
        default=None,
        description="ISO date (YYYY-MM-DD). Defaults to 2024-04-16.",
    )


class ShadowMatchRowDTO(BaseModel):
    match_id: str
    event_date: Optional[str]
    r1: float
    r2: float
    r3: float
    r4: float
    games1: int
    games2: int
    winner: int
    slot: int
    target_pre_rating: float
    target_reliability: Optional[float]
    actual_impact: float
    actual_running: float
    shadow_impact: float
    shadow_running: float


class ShadowResetDTO(BaseModel):
    player_id: str
    player_name: Optional[str]
    cutoff_date: str
    baseline_rating: float
    current_rating: Optional[float]
    current_reliability: Optional[float]
    matches_since_cutoff: int
    matches_used: int
    actual_delta: float
    actual_final_rating: float
    shadow_delta: float
    shadow_final_rating: float
    higher_of_rating: float
    partner_diversity: int
    opponent_diversity: int
    rows: List[ShadowMatchRowDTO]


@router.post(
    "/reset/shadow",
    response_model=ShadowResetDTO,
    summary="Shadow-reset simulator: replay matches since cutoff at 0% reliability",
)
def api_reset_shadow(req: ShadowResetRequest):
    from datetime import date as _date

    cutoff = None
    if req.cutoff_date:
        try:
            cutoff = _date.fromisoformat(req.cutoff_date)
        except ValueError:
            raise HTTPException(status_code=400, detail="cutoff_date must be YYYY-MM-DD")
    try:
        summary = shadow_svc.simulate(
            dupr_id=req.dupr_id,
            baseline_rating=req.baseline_rating,
            cutoff=cutoff,
        )
    except shadow_svc.ShadowUnavailable as e:
        raise HTTPException(status_code=503, detail=str(e))
    return ShadowResetDTO(**summary.to_dict())
