"""
Public REST API (JSON).

Read endpoints are open. Write endpoints require `JUPR_WRITE_API_KEY` when set.
OpenAPI is auto-generated by FastAPI at /api/docs and /api/openapi.json.
"""

from __future__ import annotations

from typing import List, Optional

from fastapi import APIRouter, Depends, HTTPException, Query, Request, status
from pydantic import BaseModel, Field
from sqlalchemy.orm import Session

from web.auth import require_write_key
from web.db import get_session
from web.models import JuprPlayer
from web.services import forecast as forecast_svc
from web.services import fupr as fupr_svc
from web.services import jupr as jupr_svc

router = APIRouter(prefix="/api", tags=["api"])


# ---------- schemas -----------------------------------------------------------

class ForecastRequest(BaseModel):
    r1: float = Field(..., ge=1.0, le=8.5)
    r2: float = Field(..., ge=1.0, le=8.5)
    r3: float = Field(..., ge=1.0, le=8.5)
    r4: float = Field(..., ge=1.0, le=8.5)
    target: int = Field(11, ge=7, le=21)
    rel1: Optional[float] = None
    rel2: Optional[float] = None
    rel3: Optional[float] = None
    rel4: Optional[float] = None


class PlayerImpactDTO(BaseModel):
    player: int
    pre_rating: float
    delta: float
    post_rating: float


class ForecastRowDTO(BaseModel):
    games1: int
    games2: int
    winner: int
    expected_games_team1: float
    impacts: List[PlayerImpactDTO]


class ForecastResponse(BaseModel):
    expected_games_team1: float
    rows: List[ForecastRowDTO]


class JuprPlayerDTO(BaseModel):
    id: int
    full_name: str
    dupr_id: Optional[str] = None
    seed_rating: float
    seed_reliability: float


class CreatePlayerRequest(BaseModel):
    full_name: str = Field(..., min_length=1, max_length=128)
    seed_rating: float = Field(3.0, ge=1.0, le=8.5)
    seed_reliability: float = Field(50.0, ge=0.0, le=100.0)
    dupr_id: Optional[str] = Field(default=None, max_length=64)


class RecordGameRequest(BaseModel):
    team1: List[int] = Field(..., min_length=2, max_length=2)
    team2: List[int] = Field(..., min_length=2, max_length=2)
    games1: int = Field(..., ge=0)
    games2: int = Field(..., ge=0)
    notes: Optional[str] = Field(default=None, max_length=500)


class JuprRatingDTO(BaseModel):
    player_id: int
    full_name: str
    seed_rating: float
    current_rating: float
    games_played: int
    last_delta: Optional[float] = None


class GameDTO(BaseModel):
    id: int
    team1: List[int]
    team2: List[int]
    pre_ratings: List[float]
    games1: int
    games2: int
    winner: int
    played_at: str


class FuprVoteRequest(BaseModel):
    rating: float = Field(..., ge=fupr_svc.MIN_RATING, le=fupr_svc.MAX_RATING)
    confidence: int = Field(3, ge=1, le=5)
    comment: Optional[str] = Field(default=None, max_length=280)


class FuprAggregateDTO(BaseModel):
    player_id: int
    count: int
    weighted_mean: Optional[float] = None
    median: Optional[float] = None
    histogram: dict


# ---------- forecast ----------------------------------------------------------

@router.post("/forecast", response_model=ForecastResponse, summary="Forecast rating impact for every score")
def api_forecast(req: ForecastRequest):
    rows = forecast_svc.forecast_matrix(
        req.r1, req.r2, req.r3, req.r4,
        target=req.target,
        rel1=req.rel1, rel2=req.rel2, rel3=req.rel3, rel4=req.rel4,
    )
    return ForecastResponse(
        expected_games_team1=rows[0].expected_games_team1 if rows else 0.0,
        rows=[
            ForecastRowDTO(
                games1=row.games1,
                games2=row.games2,
                winner=row.winner,
                expected_games_team1=row.expected_games_team1,
                impacts=[
                    PlayerImpactDTO(
                        player=imp.player,
                        pre_rating=imp.pre_rating,
                        delta=imp.delta,
                        post_rating=imp.post_rating,
                    )
                    for imp in row.impacts
                ],
            )
            for row in rows
        ],
    )


# ---------- JUPR players ------------------------------------------------------

def _player_to_dto(p: JuprPlayer) -> JuprPlayerDTO:
    return JuprPlayerDTO(
        id=p.id,
        full_name=p.full_name,
        dupr_id=p.dupr_id,
        seed_rating=p.seed_rating,
        seed_reliability=p.seed_reliability,
    )


@router.get("/jupr/players", response_model=List[JuprPlayerDTO])
def list_players(
    q: Optional[str] = Query(default=None, description="Substring search on full_name"),
    limit: int = Query(default=50, ge=1, le=200),
    session: Session = Depends(get_session),
):
    from sqlalchemy import select as _sel

    stmt = _sel(JuprPlayer).order_by(JuprPlayer.full_name).limit(limit)
    if q:
        stmt = _sel(JuprPlayer).where(JuprPlayer.full_name.ilike(f"%{q}%")).order_by(JuprPlayer.full_name).limit(limit)
    rows = session.execute(stmt).scalars().all()
    return [_player_to_dto(p) for p in rows]


@router.post(
    "/jupr/players",
    response_model=JuprPlayerDTO,
    status_code=status.HTTP_201_CREATED,
    dependencies=[Depends(require_write_key)],
)
def create_player(req: CreatePlayerRequest, session: Session = Depends(get_session)):
    p = jupr_svc.create_player(
        session,
        full_name=req.full_name,
        seed_rating=req.seed_rating,
        seed_reliability=req.seed_reliability,
        dupr_id=req.dupr_id,
    )
    return _player_to_dto(p)


@router.get("/jupr/players/{player_id}", response_model=JuprRatingDTO)
def get_player_rating(player_id: int, session: Session = Depends(get_session)):
    r = jupr_svc.get_rating(session, player_id)
    if r is None:
        raise HTTPException(status_code=404, detail="player not found")
    return JuprRatingDTO(
        player_id=r.player_id,
        full_name=r.full_name,
        seed_rating=r.seed_rating,
        current_rating=r.current_rating,
        games_played=r.games_played,
        last_delta=r.last_delta,
    )


@router.get("/jupr/players/{player_id}/games", response_model=List[GameDTO])
def get_player_games(
    player_id: int,
    limit: int = Query(default=50, ge=1, le=200),
    session: Session = Depends(get_session),
):
    games = jupr_svc.recent_games(session, player_id=player_id, limit=limit)
    return [
        GameDTO(
            id=g.id,
            team1=[g.team1_p1_id, g.team1_p2_id],
            team2=[g.team2_p1_id, g.team2_p2_id],
            pre_ratings=[g.pre_r1, g.pre_r2, g.pre_r3, g.pre_r4],
            games1=g.games1,
            games2=g.games2,
            winner=g.winner,
            played_at=g.played_at.isoformat() if g.played_at else "",
        )
        for g in games
    ]


# ---------- JUPR games --------------------------------------------------------

@router.post(
    "/jupr/games",
    response_model=GameDTO,
    status_code=status.HTTP_201_CREATED,
    dependencies=[Depends(require_write_key)],
)
def record_game(req: RecordGameRequest, session: Session = Depends(get_session)):
    try:
        g = jupr_svc.record_game(
            session,
            team1=req.team1,
            team2=req.team2,
            games1=req.games1,
            games2=req.games2,
            notes=req.notes,
        )
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e))
    return GameDTO(
        id=g.id,
        team1=[g.team1_p1_id, g.team1_p2_id],
        team2=[g.team2_p1_id, g.team2_p2_id],
        pre_ratings=[g.pre_r1, g.pre_r2, g.pre_r3, g.pre_r4],
        games1=g.games1,
        games2=g.games2,
        winner=g.winner,
        played_at=g.played_at.isoformat() if g.played_at else "",
    )


@router.get("/jupr/leaderboard", response_model=List[JuprRatingDTO])
def api_leaderboard(
    limit: int = Query(default=50, ge=1, le=200),
    session: Session = Depends(get_session),
):
    board = jupr_svc.leaderboard(session, limit=limit)
    return [
        JuprRatingDTO(
            player_id=r.player_id,
            full_name=r.full_name,
            seed_rating=r.seed_rating,
            current_rating=r.current_rating,
            games_played=r.games_played,
            last_delta=r.last_delta,
        )
        for r in board
    ]


# ---------- FUPR --------------------------------------------------------------

def _voter_key(request: Request) -> str:
    # Vercel puts the client IP in x-forwarded-for; fall back to peer addr.
    xff = request.headers.get("x-forwarded-for", "")
    if xff:
        return xff.split(",")[0].strip()
    return request.client.host if request.client else "anon"


@router.get("/fupr/{player_id}", response_model=FuprAggregateDTO)
def api_fupr_aggregate(player_id: int, session: Session = Depends(get_session)):
    agg = fupr_svc.aggregate(session, player_id)
    return FuprAggregateDTO(
        player_id=agg.player_id,
        count=agg.count,
        weighted_mean=agg.weighted_mean,
        median=agg.median,
        histogram=agg.histogram,
    )


@router.post("/fupr/{player_id}/votes", status_code=status.HTTP_201_CREATED)
def api_fupr_vote(
    player_id: int,
    req: FuprVoteRequest,
    request: Request,
    session: Session = Depends(get_session),
):
    # Confirm player exists
    p = session.get(JuprPlayer, player_id)
    if p is None:
        raise HTTPException(status_code=404, detail="player not found")
    try:
        fupr_svc.cast_vote(
            session,
            player_id=player_id,
            rating=req.rating,
            confidence=req.confidence,
            voter_key=_voter_key(request),
            comment=req.comment,
        )
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e))
    agg = fupr_svc.aggregate(session, player_id)
    return FuprAggregateDTO(
        player_id=agg.player_id,
        count=agg.count,
        weighted_mean=agg.weighted_mean,
        median=agg.median,
        histogram=agg.histogram,
    )


@router.get("/health")
def health():
    return {"status": "ok", "service": "duprly-web"}
