name: Deploy to Google Apps Script

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install clasp
        run: npm install -g @google/clasp

      - name: Setup clasp credentials
        env:
          CLASP_TOKEN: ${{ secrets.CLASP_TOKEN }}
        run: |
          echo "$CLASP_TOKEN" > ~/.clasprc.json

      - name: Setup DUPR credentials in Apps Script
        env:
          DUPR_USERNAME: ${{ secrets.DUPR_USERNAME }}
          DUPR_PASSWORD: ${{ secrets.DUPR_PASSWORD }}
        run: |
          # Create a temporary script to set credentials
          cat > setup_credentials.js << 'EOF'
          const { execSync } = require('child_process');

          // Set credentials in Google Apps Script
          const script = `
          function setupCredentialsFromCI() {
            PropertiesService.getScriptProperties().setProperties({
              'DUPR_USERNAME': '${process.env.DUPR_USERNAME}',
              'DUPR_PASSWORD': '${process.env.DUPR_PASSWORD}'
            });
            console.log('Credentials set from CI/CD');
          }
          `;

          // Write to a temporary file and push
          require('fs').writeFileSync('apps-script/SetupCredentials.gs', script);
          EOF

          node setup_credentials.js

      - name: Push to Google Apps Script
        run: |
          clasp push --force

      - name: GitFlow Deployment
        run: |
          # Get git info for deployment
          GIT_COMMIT=$(git rev-parse --short HEAD)
          GIT_MESSAGE=$(git log -1 --pretty=format:"%s")
          BRANCH=$(git branch --show-current)

          # Determine deployment type based on branch
          if [[ "$BRANCH" == "main" || "$BRANCH" == "master" ]]; then
            DEPLOY_TYPE="PRODUCTION"
            VERSION_PREFIX="PROD"
          elif [[ "$BRANCH" == "develop" || "$BRANCH" == "dev" ]]; then
            DEPLOY_TYPE="STAGING"
            VERSION_PREFIX="STAGING"
          elif [[ "$BRANCH" == feature/* || "$BRANCH" == bugfix/* || "$BRANCH" == hotfix/* ]]; then
            DEPLOY_TYPE="FEATURE"
            VERSION_PREFIX="FEATURE"
          else
            DEPLOY_TYPE="DEVELOPMENT"
            VERSION_PREFIX="DEV"
          fi

          # Create version with GitFlow info
          clasp version "$VERSION_PREFIX: $GIT_COMMIT - $GIT_MESSAGE"

          # Create deployment with GitFlow info
          clasp deploy --description "$DEPLOY_TYPE: $GIT_COMMIT - $GIT_MESSAGE (Branch: $BRANCH)"

      - name: Run tests (optional)
        run: |
          # Add any testing commands here
          echo "Running tests..."
